title: "Event Presentations"
author:
  name: "Joelle El Homsi"
  email: "joelleelhomsi@gmail.com"

description: >
  A platform to view and download presentations and documents from events organized by Joelle El Homsi. Browse through the events and access the materials easily.

# Build settings

theme: minima

# Add remote_theme if you want the latest Minima version.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

header_pages:
  - index.md
  # Add more pages here if needed, e.g., - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

minima:
  skin: auto  # Automatically switches between light and dark based on user's system settings.

  # Date format for posts and events.
  date_format: "%b %d, %Y"

# Site-wide customization options.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Social media links (optional).
#social_links:
#  - { platform: github, user_url: "https://github.com/JJoellee" }
#  - { platform: linkedin, user_url: "https://www.linkedin.com/in/joelleelhomsi/" }

# Additional configurations.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
